name: sistema_escalas_front
description: "Aplicativo de escalas da Policia Militar"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  provider: ^6.1.2
  flutter_slidable: ^4.0.3
  camera: ^0.12.1
  path_provider: ^2.1.6
  path: ^1.9.1
  flutter_native_splash: ^2.4.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo_policia_militar.png

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/logo_policia_militar.png"

  android_12:
    color: "#FFFFFF"
    image: "assets/logo_policia_militar.png"
